sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "0.12"
before_install:
  - npm i -g npm@^2.0.0
  - pip install codecov
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - codecov
